export { sendEmail, type EmailMessage, type SendResult } from "./send";
export {
  scanSummaryEmail,
  failureAlertEmail,
  downAlertEmail,
  recoveryAlertEmail,
  sslExpiryAlertEmail,
  weeklyReportEmail,
  workspaceInviteEmail,
  performanceDropEmail,
  type Severity,
  type ChangeLine,
  type ScanSummaryData,
  type FailureAlertData,
  type DownAlertData,
  type RecoveryAlertData,
  type SslExpiryAlertData,
  type WeeklyReportData,
  type WeeklySeverityCount,
  type WeeklyLighthouseScores,
  type WorkspaceInviteData,
  type PerformanceDropData,
  type PerformanceDropSnapshot,
} from "./templates";
