export { sendEmail, type EmailMessage, type SendResult } from "./send";
export {
  scanSummaryEmail,
  failureAlertEmail,
  deployVerdictEmail,
  type DeployVerdictData,
  clientReportDeliveryEmail,
  type ClientReportDeliveryData,
  downAlertEmail,
  recoveryAlertEmail,
  workerDbOutageEmail,
  workerDbRecoveryEmail,
  sslExpiryAlertEmail,
  weeklyReportEmail,
  workspaceInviteEmail,
  welcomeEmail,
  appAccessApprovedEmail,
  performanceDropEmail,
  renewalReminderEmail,
  type RenewalReminderData,
  type Severity,
  type ChangeLine,
  type ScanSummaryData,
  type FailureAlertData,
  type DownAlertData,
  type RecoveryAlertData,
  type WorkerDbOutageData,
  type WorkerDbRecoveryData,
  type SslExpiryAlertData,
  type WeeklyReportData,
  type WeeklySeverityCount,
  type WeeklyLighthouseScores,
  type WorkspaceInviteData,
  type WelcomeEmailData,
  type AppAccessApprovedData,
  type PerformanceDropData,
  type PerformanceDropSnapshot,
} from "./templates";
