/**
 * GENERATED by scripts/generate-notices.mjs - do not edit by hand.
 * Run `npm run notices` after changing dependencies.
 *
 * The 212 open-source packages that ship inside the app, for the
 * Settings -> Open source licences screen. Full licence texts live in
 * THIRD-PARTY-NOTICES.md at the repo root.
 */

export interface ThirdPartyPackage {
  name: string;
  version: string;
  license: string;
  copyright?: string;
}

export const THIRD_PARTY_PACKAGES: readonly ThirdPartyPackage[] = [
  {
    "name": "@adobe/css-tools",
    "version": "4.5.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2012 TJ Holowaychuk <tj@vision-media.ca>"
  },
  {
    "name": "@babel/code-frame",
    "version": "7.29.7",
    "license": "MIT",
    "copyright": "Copyright (c) 2014-present Sebastian McKenzie and other contributors"
  },
  {
    "name": "@babel/compat-data",
    "version": "7.29.7",
    "license": "MIT",
    "copyright": "Copyright (c) 2014-present Sebastian McKenzie and other contributors"
  },
  {
    "name": "@babel/core",
    "version": "7.29.7",
    "license": "MIT",
    "copyright": "Copyright (c) 2014-present Sebastian McKenzie and other contributors"
  },
  {
    "name": "@babel/generator",
    "version": "7.29.7",
    "license": "MIT",
    "copyright": "Copyright (c) 2014-present Sebastian McKenzie and other contributors"
  },
  {
    "name": "@babel/helper-compilation-targets",
    "version": "7.29.7",
    "license": "MIT",
    "copyright": "Copyright (c) 2014-present Sebastian McKenzie and other contributors"
  },
  {
    "name": "@babel/helper-module-imports",
    "version": "7.29.7",
    "license": "MIT",
    "copyright": "Copyright (c) 2014-present Sebastian McKenzie and other contributors"
  },
  {
    "name": "@babel/helper-module-transforms",
    "version": "7.29.7",
    "license": "MIT",
    "copyright": "Copyright (c) 2014-present Sebastian McKenzie and other contributors"
  },
  {
    "name": "@babel/helper-validator-identifier",
    "version": "7.29.7",
    "license": "MIT",
    "copyright": "Copyright (c) 2014-present Sebastian McKenzie and other contributors"
  },
  {
    "name": "@babel/helper-validator-option",
    "version": "7.29.7",
    "license": "MIT",
    "copyright": "Copyright (c) 2014-present Sebastian McKenzie and other contributors"
  },
  {
    "name": "@babel/helpers",
    "version": "7.29.7",
    "license": "MIT",
    "copyright": "Copyright (c) 2014-present Sebastian McKenzie and other contributors"
  },
  {
    "name": "@babel/parser",
    "version": "7.29.7",
    "license": "MIT",
    "copyright": "Copyright (C) 2012-2014 by various contributors (see AUTHORS)"
  },
  {
    "name": "@babel/plugin-transform-modules-commonjs",
    "version": "7.29.7",
    "license": "MIT",
    "copyright": "Copyright (c) 2014-present Sebastian McKenzie and other contributors"
  },
  {
    "name": "@babel/runtime",
    "version": "7.29.7",
    "license": "MIT",
    "copyright": "Copyright (c) 2014-present Sebastian McKenzie and other contributors"
  },
  {
    "name": "@babel/template",
    "version": "7.29.7",
    "license": "MIT",
    "copyright": "Copyright (c) 2014-present Sebastian McKenzie and other contributors"
  },
  {
    "name": "@babel/traverse",
    "version": "7.29.7",
    "license": "MIT",
    "copyright": "Copyright (c) 2014-present Sebastian McKenzie and other contributors"
  },
  {
    "name": "@babel/types",
    "version": "7.29.7",
    "license": "MIT",
    "copyright": "Copyright (c) 2014-present Sebastian McKenzie and other contributors"
  },
  {
    "name": "@better-auth/core",
    "version": "1.6.23",
    "license": "MIT",
    "copyright": "Copyright (c) 2024 - present, Bereket Engida"
  },
  {
    "name": "@better-auth/expo",
    "version": "1.6.23",
    "license": "MIT",
    "copyright": "Copyright (c) 2024 - present, Bereket Engida"
  },
  {
    "name": "@better-auth/utils",
    "version": "0.4.2",
    "license": "MIT",
    "copyright": "Copyright (c) Bereket Engida"
  },
  {
    "name": "@better-fetch/fetch",
    "version": "1.3.1",
    "license": "MIT",
    "copyright": "Copyright (c) Bereket Engida"
  },
  {
    "name": "@emnapi/core",
    "version": "1.10.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2021-present Toyobayashi"
  },
  {
    "name": "@emnapi/runtime",
    "version": "1.10.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2021-present Toyobayashi"
  },
  {
    "name": "@emnapi/wasi-threads",
    "version": "1.2.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2021-present Toyobayashi"
  },
  {
    "name": "@expo-google-fonts/dm-sans",
    "version": "0.4.2",
    "license": "MIT AND OFL-1.1",
    "copyright": "Copyright (c) 2020 Expo"
  },
  {
    "name": "@expo-google-fonts/geist-mono",
    "version": "0.4.3",
    "license": "MIT AND OFL-1.1",
    "copyright": "Copyright (c) 2020 Expo"
  },
  {
    "name": "@expo-google-fonts/poppins",
    "version": "0.4.1",
    "license": "MIT AND OFL-1.1",
    "copyright": "Copyright (c) 2020 Expo"
  },
  {
    "name": "@expo/config-plugins",
    "version": "57.0.5",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "@expo/config-types",
    "version": "57.0.2",
    "license": "MIT",
    "copyright": "Copyright (c) 2020-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "@expo/dom-webview",
    "version": "57.0.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "@expo/image-utils",
    "version": "0.11.5",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "@expo/json-file",
    "version": "11.0.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "@expo/log-box",
    "version": "57.0.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "@expo/metro-runtime",
    "version": "57.0.6",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "@expo/plist",
    "version": "0.8.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "@expo/require-utils",
    "version": "57.0.5",
    "license": "MIT",
    "copyright": "Copyright (c) 2025-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "@expo/schema-utils",
    "version": "57.0.2",
    "license": "MIT",
    "copyright": "Copyright (c) 2025-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "@expo/sdk-runtime-versions",
    "version": "1.0.0",
    "license": "MIT",
    "copyright": "Copyright (c) Expo <support@expo.io>"
  },
  {
    "name": "@expo/spawn-async",
    "version": "1.8.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2015 650 Industries"
  },
  {
    "name": "@expo/ui",
    "version": "57.0.7",
    "license": "MIT",
    "copyright": "Copyright (c) 650 Industries, Inc."
  },
  {
    "name": "@jridgewell/gen-mapping",
    "version": "0.3.13",
    "license": "MIT",
    "copyright": "Copyright 2024 Justin Ridgewell <justin@ridgewell.name>"
  },
  {
    "name": "@jridgewell/remapping",
    "version": "2.3.5",
    "license": "MIT",
    "copyright": "Copyright 2024 Justin Ridgewell <justin@ridgewell.name>"
  },
  {
    "name": "@jridgewell/resolve-uri",
    "version": "3.1.2",
    "license": "MIT",
    "copyright": "Copyright 2019 Justin Ridgewell <jridgewell@google.com>"
  },
  {
    "name": "@jridgewell/sourcemap-codec",
    "version": "1.5.5",
    "license": "MIT",
    "copyright": "Copyright 2024 Justin Ridgewell <justin@ridgewell.name>"
  },
  {
    "name": "@jridgewell/trace-mapping",
    "version": "0.3.31",
    "license": "MIT",
    "copyright": "Copyright 2024 Justin Ridgewell <justin@ridgewell.name>"
  },
  {
    "name": "@napi-rs/wasm-runtime",
    "version": "1.1.6",
    "license": "MIT",
    "copyright": "Copyright (c) LongYinan"
  },
  {
    "name": "@opentelemetry/semantic-conventions",
    "version": "1.43.0",
    "license": "Apache-2.0",
    "copyright": "copyright owner or entity authorized by"
  },
  {
    "name": "@radix-ui/primitive",
    "version": "1.1.5",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-collection",
    "version": "1.1.12",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-compose-refs",
    "version": "1.1.3",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-context",
    "version": "1.2.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-dialog",
    "version": "1.1.19",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-direction",
    "version": "1.1.2",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-dismissable-layer",
    "version": "1.1.15",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-focus-guards",
    "version": "1.1.4",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-focus-scope",
    "version": "1.1.12",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-id",
    "version": "1.1.2",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-portal",
    "version": "1.1.13",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-presence",
    "version": "1.1.7",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-primitive",
    "version": "2.1.7",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-roving-focus",
    "version": "1.1.15",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-slot",
    "version": "1.3.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-tabs",
    "version": "1.1.17",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-use-callback-ref",
    "version": "1.1.2",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-use-controllable-state",
    "version": "1.2.3",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-use-effect-event",
    "version": "0.0.3",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-use-is-hydrated",
    "version": "0.1.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@radix-ui/react-use-layout-effect",
    "version": "1.1.2",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 WorkOS"
  },
  {
    "name": "@react-native-async-storage/async-storage",
    "version": "2.2.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present, Facebook, Inc."
  },
  {
    "name": "@react-native-masked-view/masked-view",
    "version": "0.3.2",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present, Facebook, Inc."
  },
  {
    "name": "@react-native/normalize-colors",
    "version": "0.86.0",
    "license": "MIT"
  },
  {
    "name": "@standard-schema/spec",
    "version": "1.1.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2024 Colin McDonnell"
  },
  {
    "name": "@testing-library/dom",
    "version": "10.4.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2017 Kent C. Dodds"
  },
  {
    "name": "@testing-library/jest-dom",
    "version": "6.9.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2017 Kent C. Dodds"
  },
  {
    "name": "@testing-library/user-event",
    "version": "14.6.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2020 Giorgio Polvara"
  },
  {
    "name": "@tybys/wasm-util",
    "version": "0.10.3",
    "license": "MIT",
    "copyright": "Copyright (c) toyobayashi"
  },
  {
    "name": "@types/aria-query",
    "version": "5.0.4",
    "license": "MIT",
    "copyright": "Copyright (c) Microsoft Corporation."
  },
  {
    "name": "@types/react",
    "version": "19.2.17",
    "license": "MIT",
    "copyright": "Copyright (c) Microsoft Corporation."
  },
  {
    "name": "@xmldom/xmldom",
    "version": "0.8.13",
    "license": "MIT",
    "copyright": "Copyright 2019 - present Christopher J. Brody and other contributors, as listed in: https://github.com/xmldom/xmldom/graphs/contri"
  },
  {
    "name": "@xmldom/xmldom",
    "version": "0.9.10",
    "license": "MIT",
    "copyright": "Copyright 2019 - present Christopher J. Brody and other contributors, as listed in: https://github.com/xmldom/xmldom/graphs/contri"
  },
  {
    "name": "abort-controller",
    "version": "3.0.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2017 Toru Nagashima"
  },
  {
    "name": "anser",
    "version": "1.4.10",
    "license": "MIT",
    "copyright": "Copyright (c) 2012-20 Ionică Bizău <bizauionica@gmail.com> (https://ionicabizau.net)"
  },
  {
    "name": "ansi-regex",
    "version": "5.0.1",
    "license": "MIT",
    "copyright": "Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (sindresorhus.com)"
  },
  {
    "name": "ansi-styles",
    "version": "5.2.0",
    "license": "MIT",
    "copyright": "Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (sindresorhus.com)"
  },
  {
    "name": "aria-hidden",
    "version": "1.2.6",
    "license": "MIT",
    "copyright": "Copyright (c) 2017 Anton Korzunov"
  },
  {
    "name": "aria-query",
    "version": "5.3.0",
    "license": "Apache-2.0",
    "copyright": "copyright owner or entity authorized by"
  },
  {
    "name": "badgin",
    "version": "1.2.3",
    "license": "MIT",
    "copyright": "Copyright (c) Julian Hundeloh"
  },
  {
    "name": "base64-js",
    "version": "1.5.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2014 Jameson Little"
  },
  {
    "name": "better-auth",
    "version": "1.6.23",
    "license": "MIT",
    "copyright": "Copyright (c) 2024 - present, Bereket Engida"
  },
  {
    "name": "better-call",
    "version": "1.3.7",
    "license": "MIT",
    "copyright": "Copyright (c) 2025 Bereket Engida"
  },
  {
    "name": "bplist-creator",
    "version": "0.1.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2012 Near Infinity Corporation"
  },
  {
    "name": "bplist-parser",
    "version": "0.3.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2012 Near Infinity Corporation"
  },
  {
    "name": "browserslist",
    "version": "4.28.6",
    "license": "MIT",
    "copyright": "Copyright 2014 Andrey Sitnik <andrey@sitnik.es> and other contributors"
  },
  {
    "name": "chalk",
    "version": "4.1.2",
    "license": "MIT",
    "copyright": "Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (sindresorhus.com)"
  },
  {
    "name": "client-only",
    "version": "0.0.1",
    "license": "MIT"
  },
  {
    "name": "color",
    "version": "4.2.3",
    "license": "MIT",
    "copyright": "Copyright (c) 2012 Heather Arthur"
  },
  {
    "name": "color-convert",
    "version": "2.0.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2011-2016 Heather Arthur <fayearthur@gmail.com>"
  },
  {
    "name": "color-name",
    "version": "1.1.4",
    "license": "MIT",
    "copyright": "Copyright (c) 2015 Dmitry Ivanov"
  },
  {
    "name": "color-string",
    "version": "1.9.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2011 Heather Arthur <fayearthur@gmail.com>"
  },
  {
    "name": "convert-source-map",
    "version": "2.0.0",
    "license": "MIT",
    "copyright": "Copyright 2013 Thorsten Lorenz."
  },
  {
    "name": "cross-spawn",
    "version": "7.0.6",
    "license": "MIT",
    "copyright": "Copyright (c) 2018 Made With MOXY Lda <hello@moxy.studio>"
  },
  {
    "name": "css.escape",
    "version": "1.5.1",
    "license": "MIT",
    "copyright": "Copyright (c) Mathias Bynens"
  },
  {
    "name": "debug",
    "version": "4.4.3",
    "license": "MIT",
    "copyright": "Copyright (c) 2014-2017 TJ Holowaychuk <tj@vision-media.ca>"
  },
  {
    "name": "decode-uri-component",
    "version": "0.2.2",
    "license": "MIT",
    "copyright": "Copyright (c) 2017, Sam Verschueren <sam.verschueren@gmail.com> (github.com/SamVerschueren)"
  },
  {
    "name": "dequal",
    "version": "2.0.3",
    "license": "MIT",
    "copyright": "Copyright (c) Luke Edwards <luke.edwards05@gmail.com> (lukeed.com)"
  },
  {
    "name": "detect-node-es",
    "version": "1.1.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2017 Ilya Kantor"
  },
  {
    "name": "dom-accessibility-api",
    "version": "0.6.3",
    "license": "MIT",
    "copyright": "Copyright (c) 2020 Sebastian Silbermann"
  },
  {
    "name": "dom-accessibility-api",
    "version": "0.5.16",
    "license": "MIT",
    "copyright": "Copyright (c) 2020 Sebastian Silbermann"
  },
  {
    "name": "escape-string-regexp",
    "version": "4.0.0",
    "license": "MIT",
    "copyright": "Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (https://sindresorhus.com)"
  },
  {
    "name": "event-target-shim",
    "version": "5.0.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2015 Toru Nagashima"
  },
  {
    "name": "expo",
    "version": "57.0.7",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "expo-application",
    "version": "57.0.3",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "expo-constants",
    "version": "57.0.18",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "expo-device",
    "version": "57.0.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "expo-font",
    "version": "57.0.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "expo-glass-effect",
    "version": "57.0.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "expo-image",
    "version": "57.0.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "expo-linear-gradient",
    "version": "57.0.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "expo-linking",
    "version": "57.0.3",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "expo-notifications",
    "version": "57.0.18",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "expo-router",
    "version": "57.0.7",
    "license": "MIT",
    "copyright": "Copyright (c) 650 Industries, Inc."
  },
  {
    "name": "expo-secure-store",
    "version": "57.0.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "expo-server",
    "version": "57.0.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "expo-splash-screen",
    "version": "57.0.4",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "expo-status-bar",
    "version": "57.0.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "expo-symbols",
    "version": "57.0.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "expo-system-ui",
    "version": "57.0.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "expo-web-browser",
    "version": "57.0.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2015-present 650 Industries, Inc. (aka Expo)"
  },
  {
    "name": "fast-deep-equal",
    "version": "3.1.3",
    "license": "MIT",
    "copyright": "Copyright (c) 2017 Evgeny Poberezkin"
  },
  {
    "name": "filter-obj",
    "version": "1.1.0",
    "license": "MIT",
    "copyright": "Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (sindresorhus.com)"
  },
  {
    "name": "fontfaceobserver",
    "version": "2.3.0",
    "license": "BSD-2-Clause",
    "copyright": "Copyright (c) 2014 - Bram Stein"
  },
  {
    "name": "gensync",
    "version": "1.0.0-beta.2",
    "license": "MIT",
    "copyright": "Copyright 2018 Logan Smyth <loganfsmyth@gmail.com>"
  },
  {
    "name": "getenv",
    "version": "2.0.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2012-2019 Christoph Tavan <dev@tavan.de>"
  },
  {
    "name": "glob",
    "version": "13.0.6",
    "license": "BlueOak-1.0.0",
    "copyright": "Copyright\n\nEach contributor licenses you to do everything with this"
  },
  {
    "name": "indent-string",
    "version": "4.0.0",
    "license": "MIT",
    "copyright": "Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (sindresorhus.com)"
  },
  {
    "name": "invariant",
    "version": "2.2.4",
    "license": "MIT",
    "copyright": "Copyright (c) 2013-present, Facebook, Inc."
  },
  {
    "name": "is-arrayish",
    "version": "0.3.4",
    "license": "MIT",
    "copyright": "Copyright (c) 2015 JD Ballard"
  },
  {
    "name": "is-plain-obj",
    "version": "2.1.0",
    "license": "MIT",
    "copyright": "Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (sindresorhus.com)"
  },
  {
    "name": "isexe",
    "version": "2.0.0",
    "license": "ISC",
    "copyright": "Copyright (c) Isaac Z. Schlueter and Contributors"
  },
  {
    "name": "jimp-compact",
    "version": "0.16.1",
    "license": "MIT"
  },
  {
    "name": "jose",
    "version": "6.2.3",
    "license": "MIT",
    "copyright": "Copyright (c) 2018 Filip Skokan"
  },
  {
    "name": "js-tokens",
    "version": "4.0.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2014, 2015, 2016, 2017, 2018 Simon Lydell"
  },
  {
    "name": "jsesc",
    "version": "3.1.0",
    "license": "MIT",
    "copyright": "Copyright (c) Mathias Bynens"
  },
  {
    "name": "json5",
    "version": "2.2.3",
    "license": "MIT",
    "copyright": "Copyright (c) 2012-2018 Aseem Kishore, and [others]."
  },
  {
    "name": "kysely",
    "version": "0.29.4",
    "license": "MIT",
    "copyright": "Copyright (c) 2022 Sami Koskimäki"
  },
  {
    "name": "lru-cache",
    "version": "5.1.1",
    "license": "ISC",
    "copyright": "Copyright (c) Isaac Z. Schlueter and Contributors"
  },
  {
    "name": "lru-cache",
    "version": "11.5.2",
    "license": "ISC",
    "copyright": "Copyright (c) Isaac Z. Schlueter and Contributors"
  },
  {
    "name": "lucide-react-native",
    "version": "1.25.0",
    "license": "ISC",
    "copyright": "Copyright (c) 2026 Lucide Icons and Contributors"
  },
  {
    "name": "lz-string",
    "version": "1.5.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2013 pieroxy"
  },
  {
    "name": "merge-options",
    "version": "3.0.4",
    "license": "MIT",
    "copyright": "Copyright (c) Michael Mayer <michael@schnittstabil.de>"
  },
  {
    "name": "min-indent",
    "version": "1.0.1",
    "license": "MIT",
    "copyright": "Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (sindresorhus.com), James Kyle <me@thejameskyle.com> (thejameskyle.com)"
  },
  {
    "name": "minimatch",
    "version": "10.2.5",
    "license": "BlueOak-1.0.0",
    "copyright": "Copyright\n\nEach contributor licenses you to do everything with this"
  },
  {
    "name": "minipass",
    "version": "7.1.3",
    "license": "BlueOak-1.0.0",
    "copyright": "Copyright\n\nEach contributor licenses you to do everything with this"
  },
  {
    "name": "nanoid",
    "version": "3.3.16",
    "license": "MIT",
    "copyright": "Copyright 2017 Andrey Sitnik <andrey@sitnik.ru>"
  },
  {
    "name": "nanostores",
    "version": "1.4.0",
    "license": "MIT",
    "copyright": "Copyright 2020 Andrey Sitnik <andrey@sitnik.es>"
  },
  {
    "name": "parse-png",
    "version": "2.1.0",
    "license": "MIT",
    "copyright": "Copyright (c) Kevin Mårtensson <kevinmartensson@gmail.com> (github.com/kevva)"
  },
  {
    "name": "path-key",
    "version": "3.1.1",
    "license": "MIT",
    "copyright": "Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (sindresorhus.com)"
  },
  {
    "name": "path-scurry",
    "version": "2.0.2",
    "license": "BlueOak-1.0.0",
    "copyright": "Copyright\n\nEach contributor licenses you to do everything with this"
  },
  {
    "name": "picocolors",
    "version": "1.1.1",
    "license": "ISC",
    "copyright": "Copyright (c) 2021-2024 Oleksii Raspopov, Kostiantyn Denysov, Anton Verinov"
  },
  {
    "name": "plist",
    "version": "3.1.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2010-2017 Nathan Rajlich <nathan@tootallnate.net>"
  },
  {
    "name": "pngjs",
    "version": "3.4.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2015 Luke Page & Original Contributors"
  },
  {
    "name": "pretty-format",
    "version": "29.7.0",
    "license": "MIT",
    "copyright": "Copyright (c) Meta Platforms, Inc. and affiliates."
  },
  {
    "name": "pretty-format",
    "version": "27.5.1",
    "license": "MIT",
    "copyright": "Copyright (c) Meta Platforms, Inc. and affiliates."
  },
  {
    "name": "query-string",
    "version": "7.1.3",
    "license": "MIT",
    "copyright": "Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (http://sindresorhus.com)"
  },
  {
    "name": "react",
    "version": "19.2.3",
    "license": "MIT",
    "copyright": "Copyright (c) Meta Platforms, Inc. and affiliates."
  },
  {
    "name": "react-dom",
    "version": "19.2.3",
    "license": "MIT",
    "copyright": "Copyright (c) Meta Platforms, Inc. and affiliates."
  },
  {
    "name": "react-fast-compare",
    "version": "3.2.2",
    "license": "MIT",
    "copyright": "Copyright (c) 2018 Formidable Labs"
  },
  {
    "name": "react-is",
    "version": "17.0.2",
    "license": "MIT",
    "copyright": "Copyright (c) Meta Platforms, Inc. and affiliates."
  },
  {
    "name": "react-is",
    "version": "19.2.7",
    "license": "MIT",
    "copyright": "Copyright (c) Meta Platforms, Inc. and affiliates."
  },
  {
    "name": "react-native",
    "version": "0.86.0",
    "license": "MIT",
    "copyright": "Copyright (c) Meta Platforms, Inc. and affiliates."
  },
  {
    "name": "react-native-drawer-layout",
    "version": "4.2.8",
    "license": "MIT",
    "copyright": "Copyright (c) 2017 React Native Community"
  },
  {
    "name": "react-native-gesture-handler",
    "version": "2.32.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2016 Software Mansion <swmansion.com>"
  },
  {
    "name": "react-native-reanimated",
    "version": "4.5.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2016 Software Mansion <swmansion.com>"
  },
  {
    "name": "react-native-safe-area-context",
    "version": "5.7.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2019 Th3rd Wave"
  },
  {
    "name": "react-native-screens",
    "version": "4.25.2",
    "license": "MIT",
    "copyright": "Copyright (c) 2018 Software Mansion <swmansion.com>"
  },
  {
    "name": "react-native-svg",
    "version": "15.15.5",
    "license": "MIT",
    "copyright": "Copyright (c) [2015-2016] [Horcrux]"
  },
  {
    "name": "react-native-web",
    "version": "0.21.2",
    "license": "MIT",
    "copyright": "Copyright (c) Nicolas Gallagher."
  },
  {
    "name": "react-native-worklets",
    "version": "0.10.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2024 nobody"
  },
  {
    "name": "react-remove-scroll",
    "version": "2.7.2",
    "license": "MIT",
    "copyright": "Copyright (c) 2017 Anton Korzunov"
  },
  {
    "name": "react-remove-scroll-bar",
    "version": "2.3.8",
    "license": "MIT",
    "copyright": "Copyright (c) Anton Korzunov <thekashey@gmail.com>"
  },
  {
    "name": "react-style-singleton",
    "version": "2.2.3",
    "license": "MIT",
    "copyright": "Copyright (c) 2017 Anton Korzunov"
  },
  {
    "name": "redent",
    "version": "3.0.0",
    "license": "MIT",
    "copyright": "Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (sindresorhus.com)"
  },
  {
    "name": "semver",
    "version": "6.3.1",
    "license": "ISC",
    "copyright": "Copyright (c) Isaac Z. Schlueter and Contributors"
  },
  {
    "name": "semver",
    "version": "7.8.5",
    "license": "ISC",
    "copyright": "Copyright (c) Isaac Z. Schlueter and Contributors"
  },
  {
    "name": "server-only",
    "version": "0.0.1",
    "license": "MIT"
  },
  {
    "name": "sf-symbols-typescript",
    "version": "2.2.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2023 Fernando Rojo"
  },
  {
    "name": "shallowequal",
    "version": "1.1.0",
    "license": "MIT",
    "copyright": "Copyright (c) 2017 Alberto Leal <mailforalberto@gmail.com> (github.com/dashed)"
  },
  {
    "name": "shebang-command",
    "version": "2.0.0",
    "license": "MIT",
    "copyright": "Copyright (c) Kevin Mårtensson <kevinmartensson@gmail.com> (github.com/kevva)"
  },
  {
    "name": "shebang-regex",
    "version": "3.0.0",
    "license": "MIT",
    "copyright": "Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (sindresorhus.com)"
  },
  {
    "name": "simple-plist",
    "version": "1.3.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2013 Joe Wollard"
  },
  {
    "name": "simple-swizzle",
    "version": "0.2.4",
    "license": "MIT",
    "copyright": "Copyright (c) 2015 Josh Junon"
  },
  {
    "name": "slugify",
    "version": "1.6.9",
    "license": "MIT",
    "copyright": "Copyright (c) Simeon Velichkov <simeonvelichkov@gmail.com>"
  },
  {
    "name": "split-on-first",
    "version": "1.1.0",
    "license": "MIT",
    "copyright": "Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (sindresorhus.com)"
  },
  {
    "name": "stacktrace-parser",
    "version": "0.1.11",
    "license": "MIT",
    "copyright": "Copyright (c) 2014-2019 Georg Tavonius"
  },
  {
    "name": "standard-navigation",
    "version": "0.0.5",
    "license": "MIT",
    "copyright": "Copyright (c) Satyajit Sahoo <satyajit.happy@gmail.com>"
  },
  {
    "name": "strict-uri-encode",
    "version": "2.0.0",
    "license": "MIT",
    "copyright": "Copyright (c) Kevin Martensson <kevinmartensson@gmail.com> (github.com/kevva)"
  },
  {
    "name": "strip-indent",
    "version": "3.0.0",
    "license": "MIT",
    "copyright": "Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (sindresorhus.com)"
  },
  {
    "name": "tslib",
    "version": "2.8.1",
    "license": "0BSD",
    "copyright": "Copyright (c) Microsoft Corporation."
  },
  {
    "name": "typescript",
    "version": "6.0.3",
    "license": "Apache-2.0",
    "copyright": "copyright owner or entity authorized by the copyright owner that is granting the License."
  },
  {
    "name": "ua-parser-js",
    "version": "0.7.41",
    "license": "MIT",
    "copyright": "Copyright (c) 2012-2025 Faisal Salman <<f@faisalman.com>>"
  },
  {
    "name": "use-callback-ref",
    "version": "1.3.3",
    "license": "MIT",
    "copyright": "Copyright (c) 2017 Anton Korzunov"
  },
  {
    "name": "use-latest-callback",
    "version": "0.2.6",
    "license": "MIT",
    "copyright": "Copyright (c) 2023 Satyajit Sahoo"
  },
  {
    "name": "use-sidecar",
    "version": "1.1.3",
    "license": "MIT",
    "copyright": "Copyright (c) 2017 Anton Korzunov"
  },
  {
    "name": "uuid",
    "version": "7.0.3",
    "license": "MIT",
    "copyright": "Copyright (c) 2010-2016 Robert Kieffer and other contributors"
  },
  {
    "name": "vaul",
    "version": "1.1.2",
    "license": "MIT",
    "copyright": "Copyright (c) 2023 Emil Kowalski"
  },
  {
    "name": "whatwg-fetch",
    "version": "3.6.20",
    "license": "MIT",
    "copyright": "Copyright (c) 2014-2023 GitHub, Inc."
  },
  {
    "name": "which",
    "version": "2.0.2",
    "license": "ISC",
    "copyright": "Copyright (c) Isaac Z. Schlueter and Contributors"
  },
  {
    "name": "xcode",
    "version": "3.0.1",
    "license": "Apache-2.0",
    "copyright": "copyright owner or entity authorized by"
  },
  {
    "name": "xml2js",
    "version": "0.6.0",
    "license": "MIT",
    "copyright": "Copyright 2010, 2011, 2012, 2013. All rights reserved."
  },
  {
    "name": "xmlbuilder",
    "version": "15.1.1",
    "license": "MIT",
    "copyright": "Copyright (c) 2013 Ozgur Ozcitak"
  },
  {
    "name": "yallist",
    "version": "3.1.1",
    "license": "ISC",
    "copyright": "Copyright (c) Isaac Z. Schlueter and Contributors"
  },
  {
    "name": "zod",
    "version": "4.4.3",
    "license": "MIT",
    "copyright": "Copyright (c) 2025 Colin McDonnell"
  }
] as const;

/** Licence id -> how many shipped packages use it, most common first. */
export const LICENSE_SUMMARY: readonly (readonly [string, number])[] = [["MIT",190],["ISC",9],["Apache-2.0",4],["BlueOak-1.0.0",4],["MIT AND OFL-1.1",3],["0BSD",1],["BSD-2-Clause",1]] as const;
